#ocr_configs.py
nameConfig = "--psm 7 -c preserve_inerword_spaces=1, tessedit_char_whitelist=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz."
intConfig = "--psm 7 -c tessedit_char_whitelist=0123456789"
inningsConfig = "--psm 7 -c tessedit_char_whitelist=0123456789."
teamNameConfig = "--psm 7"
scoreConfig = "--psm 7 -c tessedit_char_whitelist=0123456789"
gameConfig = "--psm 7 -c tessedit_char_whitelist=0123456789#"
traitConfig = "--psm 7 -c preserve_inerword_spaces=1, tessedit_char_whitelist=24-()AaBbcCdDeEFfgGHhiIJjkKlLmMnNoOpPrRsStTuUVvwWxyZz"
playerRatingConfig = "--psm 7 -c tessedit_char_whitelist=0123456789"
chemistryConfig = "--psm 7 -c tessedit_char_whitelist=SPICMHDRA"
priPosConfig = "--psm 7 -c tessedit_char_whitelist=123BSFCLRSP/"
secPosConfig = "--psm 7 -c tessedit_char_whitelist=123BSFCLRSPOI/ "
handConfig = "--psm 13 -c tessedit_char_whitelist=LRS"
salaryConfig = "--psm 7 -c tessedit_char_whitelist=0123456789$m."
intRetryConfig = "--oem 3 --psm 8 -c tessedit_char_whitelist=0123456789"
attRetryConfig = "--psm 8 -c tessedit_char_whitelist=0123456789"